-- 活动配置后台 建表脚本
-- 数据库: MySQL 5.7

-- 1. 活动主表
CREATE TABLE ACTIVITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_TYPE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    COVER_IMAGE VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'DRAFT',
    CREATED_BY VARCHAR(50),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. 活动-归属机构关联
CREATE TABLE ACTIVITY_ORG_REL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    ORG_CODE VARCHAR(20) NOT NULL,
    ORG_NAME VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. 活动-归属部门关联
CREATE TABLE ACTIVITY_DEPT_REL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    DEPT_NAME VARCHAR(100),
    CONTACT_NAME VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. 页面配置
CREATE TABLE PAGE_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    CONFIG_TYPE VARCHAR(30) NOT NULL,
    CONFIG_KEY VARCHAR(100),
    CONFIG_VALUE LONGTEXT,
    WIDTH INT,
    HEIGHT INT,
    SORT_ORDER INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. 规则基础配置
CREATE TABLE RULE_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL UNIQUE,
    HAS_REWARD CHAR(1) DEFAULT 'N',
    REWARD_DELIVERY_TYPE VARCHAR(20),
    RULE_TYPE VARCHAR(30) DEFAULT 'REGISTER',
    TOTAL_CLAIM_LIMIT_ENABLED CHAR(1) DEFAULT 'N',
    TOTAL_CLAIM_LIMIT INT,
    REGION_LIMIT_ENABLED CHAR(1) DEFAULT 'N',
    MUTUAL_EXCLUSIVE_ENABLED CHAR(1) DEFAULT 'N',
    MUTUAL_EXCLUSIVE_ACTIVITY_ID BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. 活动-产品关联
CREATE TABLE ACTIVITY_PRODUCT_REL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    PRODUCT_CODE VARCHAR(20) NOT NULL,
    PRODUCT_NAME VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. 参与条件配置
CREATE TABLE PARTICIPATION_CONDITION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    CONDITION_TYPE VARCHAR(30) NOT NULL,
    PRODUCT_FILTER LONGTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. 奖励配置
CREATE TABLE REWARD_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    REWARD_TYPE VARCHAR(30) NOT NULL,
    REWARD_CODE VARCHAR(50),
    REWARD_NAME VARCHAR(100),
    REWARD_ALIAS VARCHAR(100),
    REWARD_ICON VARCHAR(500),
    STOCK INT DEFAULT 0,
    MAX_CLAIM_TIMES INT DEFAULT 1,
    OCCUPY_WIN_COUNT CHAR(1) DEFAULT 'Y',
    CONDITION_JSON LONGTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. 分享配置
CREATE TABLE SHARE_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL UNIQUE,
    SHARE_TITLE VARCHAR(100),
    SHARE_DESC VARCHAR(300),
    SHARE_ICON VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. 系统用户表
CREATE TABLE SYS_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    REAL_NAME VARCHAR(50),
    DEPT_NAME VARCHAR(100),
    STATUS CHAR(1) DEFAULT 'Y'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. 奖励领取记录
CREATE TABLE REWARD_CLAIM_RECORD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_ID BIGINT NOT NULL,
    CUSTOMER_ID VARCHAR(50),
    PHONE VARCHAR(20),
    REAL_NAME VARCHAR(50),
    REWARD_CODE VARCHAR(50),
    REWARD_NAME VARCHAR(100),
    CLAIM_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化管理员账号 (密码: admin123, BCrypt加密)
INSERT INTO SYS_USER (USERNAME, PASSWORD, REAL_NAME, DEPT_NAME, STATUS)
VALUES ('admin', '$2b$10$.BJl4x3scKSKHdaSUI3IluQ04P6z9fH1S.KJSFJY6.2UWSrMjFGg6', '管理员', '部门A', 'Y');

-- ============================================
-- 活动 ID=1 春日焕新活动 测试数据
-- ============================================

-- 活动
INSERT INTO ACTIVITY (ID, ACTIVITY_TYPE, TITLE, DESCRIPTION, START_TIME, END_TIME, STATUS, CREATED_BY)
VALUES (1, 'PAGE_REGISTER', '春日焕新活动', '诚e贷春季营销活动，新用户专享礼遇', '2026-03-01 00:00:00', '2026-05-31 23:59:59', 'PUBLISHED', 'admin');

-- 奖励配置 (5个)
INSERT INTO REWARD_CONFIG (ID, ACTIVITY_ID, REWARD_TYPE, REWARD_NAME, REWARD_ALIAS, STOCK, MAX_CLAIM_TIMES)
VALUES
(1, 1, 'POINTS',   '新人积分100', '注册奖励',     1000, 1),
(2, 1, 'COUPON',   '优惠券30元',  '实名认证奖励',   500, 1),
(3, 1, 'COUPON',   '返现50元',    '首借奖励',      300, 1),
(4, 1, 'COUPON',   '提额券200元', '额度奖励',      200, 1),
(5, 1, 'MALL_COUPON', '京东卡100元', '阶梯奖励',   100, 1);

-- 奖励领取记录 (110条，模拟真实分布)
DELIMITER //
CREATE PROCEDURE init_claim_records()
BEGIN
  DECLARE i INT DEFAULT 1;
  DECLARE r_name VARCHAR(100);
  DECLARE r_code VARCHAR(50);
  WHILE i <= 110 DO
    SET r_name = CASE (i % 5)
      WHEN 1 THEN '新人积分100'
      WHEN 2 THEN '优惠券30元'
      WHEN 3 THEN '返现50元'
      WHEN 4 THEN '提额券200元'
      ELSE '京东卡100元'
    END;
    SET r_code = CASE (i % 5)
      WHEN 1 THEN CONCAT('RC-REG-', LPAD(i, 3, '0'))
      WHEN 2 THEN CONCAT('RC-AUTH-', LPAD(i, 3, '0'))
      WHEN 3 THEN CONCAT('RC-LOAN-', LPAD(i, 3, '0'))
      WHEN 4 THEN CONCAT('RC-LIMIT-', LPAD(i, 3, '0'))
      ELSE CONCAT('RC-LADDER-', LPAD(i, 3, '0'))
    END;
    INSERT INTO REWARD_CLAIM_RECORD (ACTIVITY_ID, CUSTOMER_ID, PHONE, REAL_NAME, REWARD_CODE, REWARD_NAME, CLAIM_TIME)
    VALUES (
      1,
      CONCAT('CUST', LPAD(i, 5, '0')),
      CONCAT('138', LPAD(FLOOR(10000000 + RAND() * 90000000), 8, '0')),
      CONCAT('用户', i),
      r_code,
      r_name,
      DATE_ADD('2026-03-01 08:00:00', INTERVAL FLOOR(RAND() * 80 * 24 * 60) MINUTE)
    );
    SET i = i + 1;
  END WHILE;
END//
DELIMITER ;
CALL init_claim_records();
DROP PROCEDURE init_claim_records;
